# ex13/Makefile 

prog_ex13: where_is.o  main.o 
	gcc -Wall where_is.o main.o -o prog_ex13

where_is.o: where_is.c 
	gcc -g -Wall -c where_is.c -o where_is.o 

main.o: main.c
	gcc -g -Wall -c main.c -o main.o

run: prog_ex13
	./prog_ex13